export const testimonial = [
    {
        image: '/chuks.jpg',
        rxn: "/love.png",
        name: "John Doe",
        title: "CEO, XYZ Company",
        stars: 5,
        comment: "I have been working with LucentLabz for a while now and I must say they are the best in the business. They are very professional and always deliver on time. I will recommend them to anyone who needs a website.",
    }, 
    {
        image: '/chuks.jpg',
        rxn: "/hearts.png",
        name: "John Doe",
        title: "CEO, XYZ Company",
        stars: 5,
        comment: "I have been working with LucentLabz for a while now and I must say they are the best in the business. They are very professional and always deliver on time. I will recommend them to anyone who needs a website.",
    },
    {
        image: '/chuks.jpg',
        rxn: "/care.png",
        name: "John Doe",
        title: "CEO, XYZ Company",
        stars: 5,
        comment: "I have been working with LucentLabz for a while now and I must say they are the best in the business. They are very professional and always deliver on time. I will recommend them to anyone who needs a website.",
    },
    {
        image: '/chuks.jpg',
        rxn: "/love.png",
        name: "John Doe",
        title: "CEO, XYZ Company",
        stars: 4,
        comment: "I have been working with LucentLabz for a while now and I must say they are the best in the business. They are very professional and always deliver on time. I will recommend them to anyone who needs a website.",
    },
    {
        image: '/chuks.jpg',
        rxn: "/hearts.png",
        name: "John Doe",
        title: "CEO, XYZ Company",
        stars: 5,
        comment: "I have been working with LucentLabz for a while now and I must say they are the best in the business. They are very professional and always deliver on time. I will recommend them to anyone who needs a website.",
    }, 
    {
        image: '/chuks.jpg',
        rxn: "/love.png",
        name: "John Doe",
        title: "CEO, XYZ Company",
        stars: 5,
        comment: "I have been working with LucentLabz for a while now and I must say they are the best in the business. They are very professional and always deliver on time. I will recommend them to anyone who needs a website.",
    }
]